### ISSUE TITLE
Python version support

### ISSUE THREAD

**Issue by pacharanero** [uk-fci/nhs-number#11]
Just wondering if we should target any specific minimum version of Python for this library?
In the Travis config it is currently targeting:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

I'm not sure we need to continue with Python 2 support and the more recent updates have not been tested against 2.7
3.6 is already EOL and 3.7 is weeks away from also being EOL https://devguide.python.org/versions/

I wonder if perhaps 3.8 and above might be appropriate?

This would also allow us to use [Poetry](https://python-poetry.org/docs/) for the publication workflow (Poetry is dependent on 3.7+)

**Comment by andylaw** [comment]
3.7 was my current version when I first wrote it. I still run it in a conda environment against that version. I have no need of anything lower than that and I am actively working to move to 3.10. So, 3.8 is a little harsh for me just now but I can live with it :)

**Comment by pacharanero** [comment]
We are testing against Python 3.7 - 3.11 at the moment and this seems to be appropriate given the lifecycle of those Pythons.
