### ISSUE TITLE
Mixture of unittest and pytest tests

### ISSUE THREAD

**Issue by andylaw** [uk-fci/nhs-number#15]
We should settle on one option and just stick to that. I have no preference so we should go with whichever is the current flavour-du-jour and best supported

**Comment by pacharanero** [comment]
We have been using `pytest` a lot in our other projects so I would favour switching to that. It seems to be more popular at the moment. However one of the reasons it is more popular is that as well as adding helpful features, it can also run any `unittest` syntax tests as well, so there is no reason other than tidiness - which is a good reason IMO - to change the `unittest` stuff.

**Comment by eatyourpeas** [comment]
I agree. Pytest is great.

**Comment by andylaw** [comment]
Addressed by Pull Request #18
