### ISSUE TITLE
single-file version?

### ISSUE THREAD

**Issue by dgm3333** [uk-fci/nhs-number#28]
Is there a single-file version of this - I was going to translate it to a single file c/c++ module but the multi-file distribution in the git is a pain. It's interesting the scale of this - as I wouldn't have thought generating NHS numbers would have been a complex task...

**Comment by eatyourpeas** [comment]
My general feeling is that this somewhat out of scope for this project. There are, as they say, lots of ways to skin a cat (why do they say that?), and I think in this project we are throwing our collective weight behind python. There is no imperative to do this, except that python is very accessible, is a language familiar to the health tech and academic community, and we have PyPi which is a great resource for packages. We want colleagues engaging in health systems research, or potentially delivering clinical care, to be able to focus on building the thing, not wrangling with esoteric modulus 11 algorithms and the vaguaries of regional number ranges and so. And as with discussions elsewhere - it is built with simplicity in mind, but with complexity available if you want it. I think if there is a different use case that requires binaries/another language, that should be another project. It could for sure inherit from this one, but my view is that it is hard to maintain in the same repo and I am not that clear what the end product would look like.

**Comment by andylaw** [comment]
Not a focus for this project. The Python code here is freely available; if others want to generate a parallel C/C++ implementation then they can use this as a template if they so wish.

**Comment by andylaw** [comment]
> Not a focus for this project. The Python code here is freely available; if others want to generate a parallel C/C++ implementation then they can use this as a template if they so wish.
